### ISSUE TITLE
Refactor - Onboard

### ISSUE THREAD

**Issue by ninuxch** [swissDAO/daotic#64]
https://github.com/swissDAO/daotic/blob/460ed267dd2fa24167b86022bac7a99c1e10b656/src/SwissDAO.sol#L244

- Again use modifier.
- An additional counter is required (starting at 10000) for the next free membershipId.
- Function should check wether the member address possesses any token above 10000, L253 and subsequent checks do this.
- However: A none-member has no token, so the ID would be zero.
- Revert criteria id > 0 is much better.
- We could have modifiers for isMember and isNotMember that check this.

**Comment by ninuxch** [comment]
Addon: The generation of the membershipId on L253 will not work as intended: It leaves gaps in the id numbering, preventing efficient loops. Also it can cause collisions. Furthermore we should not rely on the address.

**Comment by tomlibert8** [comment]
The original idea was to derive the membershipID from the member address, say, each member would have the same membershipID as his address (except for the type), whereby it is impossible that someone has private keys for the address 0x01 or 0x02 and so no clash with XP and AP.

We agreed to change this to systematic membershipIDs starting with the ID 10000. Additional reason for this is that if you want to see your on-chain membership in your wallet, you have to manually add while pasting the membershipID which was very long with the original approach. Writing a five digit long number is nicer.

The refactoring is done. Modifiers added. The counter is now called next_membership_id. Instead of checking by going through all MembershipIDs, we check if the member address isn't already in the s_members array. Having no token is not the same as owning the token with id 0!
